SiteTitle: The Ancients
SiteDescription: A Lord of the Rings Online Blog
Copyright: Copyright © 2023 nullforce. All rights reserved.

GenerateSearchIndex: true
LinksUseHttps: true
Image: ./images/site-image.png

GitHubOwner: TheAncientsLotro
GitHubName: TheAncientsLotro.github.io
GitHubToken: '=> Config.FromSetting<string>("GITHUB_TOKEN")'
